# Coolify Configuration for JagaSuara Application
# This file defines the deployment configuration for Coolify

version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
      # Coolify magic variables for domain configuration
      - SERVICE_FQDN_APP=${SERVICE_FQDN_APP}
      - NEXT_PUBLIC_APP_URL=https://${SERVICE_FQDN_APP}
    networks:
      - coolify
    labels:
      # Enable Traefik proxy
      - traefik.enable=true
      
      # HTTP router configuration
      - traefik.http.routers.jagasuara-http.rule=Host(`${SERVICE_FQDN_APP}`)
      - traefik.http.routers.jagasuara-http.entryPoints=http
      - traefik.http.routers.jagasuara-http.middlewares=redirect-to-https
      
      # HTTPS router configuration
      - traefik.http.routers.jagasuara-https.rule=Host(`${SERVICE_FQDN_APP}`)
      - traefik.http.routers.jagasuara-https.entryPoints=https
      - traefik.http.routers.jagasuara-https.tls=true
      - traefik.http.routers.jagasuara-https.tls.certresolver=letsencrypt
      - traefik.http.routers.jagasuara-https.service=jagasuara-service
      
      # Service configuration
      - traefik.http.services.jagasuara-service.loadbalancer.server.port=3000
      
      # Middleware for HTTPS redirect
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true

networks:
  coolify:
    external: true
